### ISSUE TITLE
oracle.pp profile not working

### ISSUE THREAD

**Issue by wfsaxton** [sevendials/oracle-oradb#1]
I've been attempting to use the biemond/oradb puppet module for a week now and haven't been able to successfully provision a database from it yet, although I have been able to successfully install the software and create a listener .  I found your repo, via google, and attempted to do exactly what you have done here (with a few tweaks for my environment) and I still continue to get the same error.

Were you actually able to successfully provision a database with this code?

My issue seems to be that oradb::database is getting hung up on trying to find out the listener configuration.  Puppet gives an error on a "dbca" command run and, when I run the command manually, I get:
```
[oracle@generic ~]$ /oracle/product/12.2/db/bin/dbca -silent -createDatabase -responseFile /var/tmp/database_testDb_Create.rsp
[FATAL] [DBT-07505] Selected listener (LISTENER) does not exist.
   ACTION: Specify an existing listener.
[oracle@generic ~]$
```
This is because the response file that Puppet created has this entry:
```
listeners=LISTENER
```
I don't see where your repository has the "listener" configured so not sure how it could be working.

Anyway, if you aren't answer questions about this then feel free to close.  I'm just a little desperate at this point so looking for any help I can get.

**Comment by wfsaxton** [comment]
Looks like this was just a bug in the module for Oracle 12.2.

https://github.com/biemond/biemond-oradb/issues/159

It has since been resolved.

**Comment by sevendials** [comment]
Good to know, thanks.
